### ISSUE TITLE
Create a weather App

### ISSUE THREAD

**Issue by devopsjester** [devopsjester/chr-demo-weather#1]
Use prompt engineering with Copilot to do the following:

```[tasklist]
### Tasks
- [x] Get a city and state based on a zip code using the zipopotam.us API
- [x] Get the local temperature for the city and state using the openweathermap.org API
- [ ] use logging for errors and information
- [ ] use better error handling look for vulnerabilities
- [ ] move the api key to a configuration file
- [ ] prompt for a zip code if none is provided at the command line
```
